version: '2'
services:
  node:
    image: wealthwizardsengineering/ww-base-node:alpine-latest
    volumes:
      - ./:/usr/src/app:z
    working_dir: /usr/src/app

  npm:
    extends:
      service: node
    entrypoint: npm

  unit-test:
    extends:
      service: npm
    command: run test:unit:report

  client:
    extends:
      service: node
    entrypoint: /usr/src/app/src/service-listener.js
    environment:
    - WW_REQUEST_LOGGER_LEVEL=trace
    - SERVICE_REGISTRY_URL=http://10.10.56.151:3000/service-registry
    - VERSION_SERVICE_URL=http://10.10.56.151:3001/version-service
    - KUBERNETES_MASTER_URL=https://10.28.1.9
    - KUBERNETES_NAMESPACE=st
