version: '2'
services:
  node:
    image: quay.io/wealthwizards/ww-base-node:alpine-8
    volumes:
      - .:/usr/src/app:z
    working_dir: /usr/src/app

  npm:
    extends:
      service: node
    entrypoint: npm

  unit-test:
    extends:
      service: npm
    command: run test:unit

  client:
    extends:
      service: node
    entrypoint: /usr/src/app/src/service-listener.js
    env_file: .env
