version: '2'
services:
  node:
    image: quay.io/wealthwizards/ww-base-node:alpine-14
    volumes:
      - .:/usr/src/app:z
    working_dir: /usr/src/app

  yarn:
    extends:
      service: node
    entrypoint: yarn

  unit-test:
    extends:
      service: yarn
    command: run test:unit

  client:
    extends:
      service: node
    entrypoint: /usr/src/app/src/service-listener.js
    env_file: .env
    volumes:
      - .:/usr/src/app:z
      - ~/.kube:/root/.kube:z

