version: 2
jobs:
  build:
    docker:
      - image: quay.io/wealthwizards/ww-base-node:alpine-6
    working_directory: /usr/src
    steps:
      - add_ssh_keys
      - run:
          name: install-git-ssh
          command: apk update && apk add git openssh
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: lint
          command: npm run lint
      - run:
          name: dependency-check
          command: npm run dependency-check
      - run:
          name: unit-tests
          command: npm run test:unit
  buildAndDeploy:
    machine: true
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name : patch-application
          command: |
            git config --global user.email "circleci@wealthwizards.com"
            git config --global user.name "Circle CI"
            npm version patch -m "Release %s [ci skip]" > .version
      - run:
          name : build-docker-image
          command: |
            docker build -t quay.io/wealthwizards/service-listener .
            docker tag quay.io/wealthwizards/service-listener quay.io/wealthwizards/service-listener:$(cat .version)
      - deploy:
          name : deploy-git-changes
          command: git push --follow-tags
      - deploy:
          name : deploy-docker-image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS quay.io
            docker push quay.io/wealthwizards/service-listener
            docker push quay.io/wealthwizards/service-listener:$(cat .version)
  buildDockerImage:
    machine: true
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name : build-docker-image
          command: |
            docker build -t quay.io/wealthwizards/service-listener .
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - buildDockerImage:
          filters:
            branches:
              ignore: master
      - buildAndDeploy:
          requires:
            - build
          filters:
            branches:
              only: master
